# Generated by Django 6.1.1 on 2026-10-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_waiter_staff_role'),
        ('branches', '0006_branch_late_threshold_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='branches.branch')),
            ],
            options={
                'ordering': ['start_time', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='accounts.shifttemplate'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'name'), name='unique_shift_template_name_per_branch'),
        ),
    ]
