# Generated by Django 6.1.1 on 2026-09-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['id']},
        ),
    ]
