# Generated by Django 6.1.1 on 2026-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_attendance_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='favicon_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
