# Generated by Django 6.1.1 on 2026-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_favicon_url_branch_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='late_threshold_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='max_clock_ins_per_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='branch',
            name='max_clock_outs_per_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
