# Generated by Django 6.1.1 on 2026-09-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('label_en', models.CharField(max_length=100)),
                ('label_ar', models.CharField(max_length=100)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('session_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied'), ('needs-bill', 'Needs Bill')], default='empty', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='branches.branch')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
