# Generated by Django 6.1.1 on 2026-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_clear_orphaned_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
