"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    # Must be first: this is what makes `manage.py runserver` ASGI/Channels-
    # aware instead of plain WSGI.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'common',
    'accounts',
    'branches',
    'catalog',
    'tables',
    'orders',
    'inventory',
    'purchasing',
    'customers',
    'reports',
    'realtime',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# REDIS_URL unset -> single-process in-memory channel layer: fine for local
# `runserver` dev, useless across multiple worker processes. Set REDIS_URL
# for anything beyond local dev — production needs the real thing.
REDIS_URL = env('REDIS_URL', default=None)
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    # DATABASE_URL is your Neon connection string, e.g.:
    # postgresql://user:password@host/dbname?sslmode=require
    # Falls back to local sqlite when unset so `manage.py check`/`makemigrations`
    # work without needing real credentials — never used in production.
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Django REST Framework
# Pagination is configured globally here so every list endpoint across every
# app gets consistent ?page=/?page_size= behavior for free.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.StaffJWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'common.pagination.DefaultPagination',
    'PAGE_SIZE': 25,
    'EXCEPTION_HANDLER': 'common.exceptions.error_code_exception_handler',
    # Only views that set `throttle_scope` (e.g. pin-login) are actually
    # throttled — ScopedRateThrottle is a no-op for everything else.
    'DEFAULT_THROTTLE_CLASSES': ['rest_framework.throttling.ScopedRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        'pin-login': '10/min',
        # The login screen fetches its branch/staff dropdown at most once per
        # page load, so this is generous for real use and still bounds a
        # scanner enumerating staff names.
        'login-choices': '30/min',
        # Phase 13 public/customer-facing endpoints — all AllowAny, so these
        # are the only thing standing between them and abuse. ScopedRateThrottle
        # keys anonymous requests by IP.
        'menu': '60/min',
        'table-lookup': '60/min',
        # Billing endpoints are AllowAny (authenticated by the table's
        # session token), so they get their own tighter scopes. 'bill-pay'
        # covers request-pay/cancel-pay-request — a customer taps those a
        # handful of times at most. 'bill-verify' covers the callback page's
        # verification, which costs us an outbound Moyasar API call per hit.
        'bill-pay': '20/min',
        'bill-verify': '30/min',
    },
}

# Staff isn't AUTH_USER_MODEL (see accounts/models.py), so tokens carry a
# custom claim name and are resolved by accounts.authentication.StaffJWTAuthentication.
# No token_blacklist app: it hard-FKs outstanding tokens to AUTH_USER_MODEL,
# which is incompatible with Staff not being that model. Logout is therefore
# client-side (discard the tokens) — see accounts/views.py LogoutView.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=12),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'staff_id',
}

# CORS — restaurant-admin's Vite dev server needs to be listed here,
# e.g. CORS_ALLOWED_ORIGINS=http://localhost:5173
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])


# Moyasar payment gateway (orders/moyasar.py, orders/billing.py)
# ---------------------------------------------------------------
# Test vs live is ENTIRELY a matter of which keys are in .env — sk_test_…/
# pk_test_… for sandbox, sk_live_…/pk_live_… for production. There is no mode
# flag anywhere in the code, so going live never requires a deploy of new code.
#
# MOYASAR_SECRET_KEY is backend-only and must never reach a browser: it is
# read in orders/moyasar.py and nowhere else, and no serializer exposes it.
# MOYASAR_PUBLISHABLE_KEY is safe to hand out and is returned by
# POST /api/bills/request-pay/ so the customer web app needs no Moyasar
# config of its own.
#
# Defaults are blank so `manage.py check`/`migrate` work on a fresh clone;
# requesting an online payment with a blank secret returns 503
# error.paymentsNotConfigured rather than failing obscurely.
MOYASAR_SECRET_KEY = env('MOYASAR_SECRET_KEY', default='')
MOYASAR_PUBLISHABLE_KEY = env('MOYASAR_PUBLISHABLE_KEY', default='')
MOYASAR_API_BASE = env('MOYASAR_API_BASE', default='https://api.moyasar.com/v1')
# Optional shared secret echoed back in the webhook body's `secret_token`
# field. Leave blank to skip the check — verification against the Moyasar API
# is the real gate either way. See orders/moyasar.webhook_secret_matches().
MOYASAR_WEBHOOK_SECRET = env('MOYASAR_WEBHOOK_SECRET', default='')

# Every bill is charged in SAR, hard-coded in orders/billing.py. Moyasar takes
# the amount in halalas (1 SAR = 100 halalas), computed server-side from
# Decimal only. NOTE FOR GOING LIVE: catalog Product.price is a bare Decimal
# with no currency column, so every menu price in the database is assumed to
# already be in SAR. Loading a menu priced in anything else would charge the
# wrong amount.
BILL_CURRENCY = 'SAR'

# Absolute origin of the customer-facing QR web app (burger_web). Used to
# build the Moyasar callback_url the customer is redirected back to after
# 3DS/STC Pay. Must be the public origin in production, not localhost.
CUSTOMER_WEB_BASE_URL = env('CUSTOMER_WEB_BASE_URL', default='http://localhost:3000')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
