# Generated by Django 6.1.1 on 2026-09-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='branches.branch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'phone'), name='unique_phone_per_branch')],
            },
        ),
    ]
