# Generated by Django 6.1.1 on 2026-10-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_waiter_staff_role'),
        ('branches', '0004_branch_attendance_radius'),
        ('orders', '0005_idempotent_submissions_and_payments'),
        ('tables', '0003_clear_orphaned_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('pay_requested', 'Payment requested'), ('paid', 'Paid'), ('closed', 'Closed')], default='open', max_length=16)),
                ('requested_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card (at the till)'), ('online', 'Online (Moyasar)')], max_length=8)),
                ('paid_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card (at the till)'), ('online', 'Online (Moyasar)')], max_length=8)),
                ('total_at_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_requested_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='branches.branch')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_bills', to='accounts.staff')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_bills', to='accounts.staff')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='tables.table')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.bill'),
        ),
        migrations.CreateModel(
            name='MoyasarPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(max_length=24)),
                ('amount_halalas', models.PositiveIntegerField()),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('source_type', models.CharField(blank=True, max_length=24)),
                ('source_company', models.CharField(blank=True, max_length=24)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_reason', models.CharField(blank=True, max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyasar_payments', to='orders.bill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'closed'), _negated=True), fields=('table',), name='one_open_bill_per_table'),
        ),
    ]
