# Generated by Django 6.1.1 on 2026-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_variant_orderitem_variant_name_ar_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('pos', 'POS'), ('qr', 'QR'), ('web', 'Website')], default='pos', max_length=8),
        ),
    ]
